name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: swift:6.0.3
    steps:
      - uses: actions/checkout@v4
      - name: swift version
        run: swift --version
      - name: Run script
        run: swift build
