name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-6.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: swift version
        run: swift --version
      - name: Run script
        run: swift build
